INSERT INTO state.eg_role select nextval('state.seq_eg_role'), 'BPA Approver', 'BPA Approver', now(), 1, 1, now(), 0, false where not exists (select * from state.eg_role where name='BPA Approver');
insert into state.eg_role select nextval('state.seq_eg_role'),'Bpa Administrator','One who manages the masters and key Bpa data',now(),1,1,now(),0,false where not exists (select * from state.eg_role where name='Bpa Administrator');

INSERT INTO state.eg_role select nextval('state.seq_eg_role'), 'BPA Report Viewer', 'BPA Report Viewer', now(), 1, 1, now(), 0, false where not exists (select * from state.eg_role where name='BPA Report Viewer');
INSERT INTO state.eg_role select nextval('state.seq_eg_role'), 'Document Scrutiniser', 'Document Scrutiniser', now(), 1, 1, now(), 0, false where not exists (select * from state.eg_role where name='Document Scrutiniser');
INSERT INTO state.eg_role select nextval('state.seq_eg_role'), 'BPA BAR report viewer', 'Can view BAR report details', now(), 1, 1, now(), 0, false where not exists (select * from state.eg_role where name='BPA BAR report viewer');
INSERT INTO state.eg_role select nextval('state.seq_eg_role'), 'Permit Revoker', 'Permit Revoker', now(), 1, 1, now(), 0, false where not exists (select * from state.eg_role where name='Permit Revoker');
INSERT into state.eg_role select nextval('state.seq_eg_role'), 'BPA_FIRE_NOC_ROLE', 'Role for users who approve/provides a NOC from Fire department', now(), 1, 1, now(), 0, false where not exists (select * from state.eg_role where name='BPA_FIRE_NOC_ROLE');
INSERT into state.eg_role select nextval('state.seq_eg_role'), 'BPA_AIPORT_AUTH_NOC_ROLE', 'Role for users who approve/provides a NOC from Airport authority', now(), 1, 1, now(), 0, false where not exists (select * from state.eg_role where name='BPA_AIPORT_AUTH_NOC_ROLE');
INSERT into state.eg_role select nextval('state.seq_eg_role'), 'BPA_NMA_NOC_ROLE', 'Role for users who approve/provides a NOC from Heritage Conservation Committee (National Monuments Authority)', now(), 1, 1, now(), 0, false where not exists (select * from state.eg_role where name='BPA_NMA_NOC_ROLE');
INSERT into state.eg_role select nextval('state.seq_eg_role'), 'BPA_ENVIRONMENT_NOC_ROLE', 'Role for users who approve/provides a NOC from MOEF/environment clearance', now(), 1, 1, now(), 0, false where not exists (select * from state.eg_role where name='BPA_ENVIRONMENT_NOC_ROLE');
