alter table EGBPA_APPLICATION_FLOORDETAIL add column usage bigint;

ALTER TABLE EGBPA_APPLICATION_FLOORDETAIL ADD CONSTRAINT fk_propsed_bldg_floor_usage FOREIGN KEY (usage)
   REFERENCES EGBPA_USAGE (id);

alter table EGBPA_EXISTING_BUILDING_FLOORDETAIL add column usage bigint;

ALTER TABLE EGBPA_EXISTING_BUILDING_FLOORDETAIL ADD CONSTRAINT fk_exst_bldg_floor_usage FOREIGN KEY (usage)
   REFERENCES EGBPA_USAGE (id);