INSERT INTO EGBPA_BUILDING_CONSTRUCTIONSTAGE (ID,NAME,DESCRIPTION,active,VERSION,CREATEDBY,CREATEDDATE) VALUES (nextval('SEQ_EGBPA_BUILDING_CONSTRUCTIONSTAGE'),'Foundation','Foundation',true,0,1,now());
INSERT INTO EGBPA_BUILDING_CONSTRUCTIONSTAGE (ID,NAME,DESCRIPTION,active,VERSION,CREATEDBY,CREATEDDATE) VALUES (nextval('SEQ_EGBPA_BUILDING_CONSTRUCTIONSTAGE'),'Plinth','Plinth',true,0,1,now());
INSERT INTO EGBPA_BUILDING_CONSTRUCTIONSTAGE (ID,NAME,DESCRIPTION,active,VERSION,CREATEDBY,CREATEDDATE) VALUES (nextval('SEQ_EGBPA_BUILDING_CONSTRUCTIONSTAGE'),'Floors','Floors',true,0,1,now());
