ALTER TABLE EGBPA_MSTR_STAKEHOLDER ADD COLUMN demand bigint;

 ALTER TABLE EGBPA_MSTR_STAKEHOLDER  ADD CONSTRAINT fk_egbpa_mstr_stakeholder_demand FOREIGN KEY (demand)
      REFERENCES eg_demand (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION