
------------------------------------------    "New Construction"  ------------------------------------


INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='RENEWALREJECTIONREASON-01' and checklisttypeid =(select id from eg_checklist_type where code='RENEWALREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='01'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='RENEWALREJECTIONREASON-02' and checklisttypeid =(select id from eg_checklist_type where code='RENEWALREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='01'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='RENEWALREJECTIONREASON-03' and checklisttypeid =(select id from eg_checklist_type where code='RENEWALREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='01'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='RENEWALREJECTIONREASON-04' and checklisttypeid =(select id from eg_checklist_type where code='RENEWALREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='01'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='RENEWALREJECTIONREASON-05' and checklisttypeid =(select id from eg_checklist_type where code='RENEWALREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='01'), 'true', 'false', 0, 1, now(), 1, now());


-----------------------------------------  "Change in occupancy" -------------------------------------------------------------


INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='RENEWALREJECTIONREASON-01' and checklisttypeid =(select id from eg_checklist_type where code='RENEWALREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='07'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='RENEWALREJECTIONREASON-02' and checklisttypeid =(select id from eg_checklist_type where code='RENEWALREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='07'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='RENEWALREJECTIONREASON-03' and checklisttypeid =(select id from eg_checklist_type where code='RENEWALREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='07'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='RENEWALREJECTIONREASON-04' and checklisttypeid =(select id from eg_checklist_type where code='RENEWALREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='07'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='RENEWALREJECTIONREASON-05' and checklisttypeid =(select id from eg_checklist_type where code='RENEWALREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='07'), 'true', 'false', 0, 1, now(), 1, now());

----------------------------------   "Reconstruction"   ------------------------------


INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='RENEWALREJECTIONREASON-01' and checklisttypeid =(select id from eg_checklist_type where code='RENEWALREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='03'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='RENEWALREJECTIONREASON-02' and checklisttypeid =(select id from eg_checklist_type where code='RENEWALREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='03'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='RENEWALREJECTIONREASON-03' and checklisttypeid =(select id from eg_checklist_type where code='RENEWALREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='03'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='RENEWALREJECTIONREASON-04' and checklisttypeid =(select id from eg_checklist_type where code='RENEWALREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='03'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='RENEWALREJECTIONREASON-05' and checklisttypeid =(select id from eg_checklist_type where code='RENEWALREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='03'), 'true', 'false', 0, 1, now(), 1, now());

---------------------------------------------   "Alteration"   ---------------------------------------


INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='RENEWALREJECTIONREASON-01' and checklisttypeid =(select id from eg_checklist_type where code='RENEWALREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='04'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='RENEWALREJECTIONREASON-02' and checklisttypeid =(select id from eg_checklist_type where code='RENEWALREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='04'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='RENEWALREJECTIONREASON-03' and checklisttypeid =(select id from eg_checklist_type where code='RENEWALREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='04'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='RENEWALREJECTIONREASON-04' and checklisttypeid =(select id from eg_checklist_type where code='RENEWALREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='04'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='RENEWALREJECTIONREASON-05' and checklisttypeid =(select id from eg_checklist_type where code='RENEWALREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='04'), 'true', 'false', 0, 1, now(), 1, now());


---------------------------------------------------"Addition or Extension" ----------------------------------------



INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='RENEWALREJECTIONREASON-01' and checklisttypeid =(select id from eg_checklist_type where code='RENEWALREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='06'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='RENEWALREJECTIONREASON-02' and checklisttypeid =(select id from eg_checklist_type where code='RENEWALREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='06'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='RENEWALREJECTIONREASON-03' and checklisttypeid =(select id from eg_checklist_type where code='RENEWALREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='06'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='RENEWALREJECTIONREASON-04' and checklisttypeid =(select id from eg_checklist_type where code='RENEWALREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='06'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='RENEWALREJECTIONREASON-05' and checklisttypeid =(select id from eg_checklist_type where code='RENEWALREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='06'), 'true', 'false', 0, 1, now(), 1, now());

