---------------------------------------------OWNERSHIPDOCUMENTS---------------------------------------


--------------------------------New Construction------------------------------

INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where description='Application duly signed by the owner' and checklisttypeid = (select id from eg_checklist_type where code='OWNERSHIPDOCUMENTS' )), (select id from EGBPA_MSTR_SERVICETYPE where description='New Construction'),'1','0', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where description='New land deed document' and checklisttypeid = (select id from eg_checklist_type where code='OWNERSHIPDOCUMENTS' )), (select id from EGBPA_MSTR_SERVICETYPE where description='New Construction'),'1','0', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where description='New Possession certificate' and checklisttypeid = (select id from eg_checklist_type where code='OWNERSHIPDOCUMENTS' )), (select id from EGBPA_MSTR_SERVICETYPE where description='New Construction'),'1','0', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where description='New Land tax receipt' and checklisttypeid = (select id from eg_checklist_type where code='OWNERSHIPDOCUMENTS' )), (select id from EGBPA_MSTR_SERVICETYPE where description='New Construction'),'1','0', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where description='Building permit' and checklisttypeid = (select id from eg_checklist_type where code='OWNERSHIPDOCUMENTS' )), (select id from EGBPA_MSTR_SERVICETYPE where description='New Construction'),'1','0', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where description='Stage Photos' and checklisttypeid = (select id from eg_checklist_type where code='OWNERSHIPDOCUMENTS' )), (select id from EGBPA_MSTR_SERVICETYPE where description='New Construction'),'1','0', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where description='Other' and checklisttypeid = (select id from eg_checklist_type where code='OWNERSHIPDOCUMENTS' )), (select id from EGBPA_MSTR_SERVICETYPE where description='New Construction'),'1','0', 0, 1, now(), 1, now());


----------------------------------Reconstruction-------------------------------

INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where description='Application duly signed by the owner' and checklisttypeid = (select id from eg_checklist_type where code='OWNERSHIPDOCUMENTS' )), (select id from EGBPA_MSTR_SERVICETYPE where description='Reconstruction'),'1','0', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where description='New land deed document' and checklisttypeid = (select id from eg_checklist_type where code='OWNERSHIPDOCUMENTS' )), (select id from EGBPA_MSTR_SERVICETYPE where description='Reconstruction'),'1','0', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where description='New Possession certificate' and checklisttypeid = (select id from eg_checklist_type where code='OWNERSHIPDOCUMENTS' )), (select id from EGBPA_MSTR_SERVICETYPE where description='Reconstruction'),'1','0', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where description='New Land tax receipt' and checklisttypeid = (select id from eg_checklist_type where code='OWNERSHIPDOCUMENTS' )), (select id from EGBPA_MSTR_SERVICETYPE where description='Reconstruction'),'1','0', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where description='Building permit' and checklisttypeid = (select id from eg_checklist_type where code='OWNERSHIPDOCUMENTS' )), (select id from EGBPA_MSTR_SERVICETYPE where description='Reconstruction'),'1','0', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where description='Stage Photos' and checklisttypeid = (select id from eg_checklist_type where code='OWNERSHIPDOCUMENTS' )), (select id from EGBPA_MSTR_SERVICETYPE where description='Reconstruction'),'1','0', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where description='Other' and checklisttypeid = (select id from eg_checklist_type where code='OWNERSHIPDOCUMENTS' )), (select id from EGBPA_MSTR_SERVICETYPE where description='Reconstruction'),'1','0', 0, 1, now(), 1, now());



----------------------------------Alteration--------------------------------------

INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where description='Application duly signed by the owner' and checklisttypeid = (select id from eg_checklist_type where code='OWNERSHIPDOCUMENTS' )), (select id from EGBPA_MSTR_SERVICETYPE where description='Alteration'),'1','0', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where description='New land deed document' and checklisttypeid = (select id from eg_checklist_type where code='OWNERSHIPDOCUMENTS' )), (select id from EGBPA_MSTR_SERVICETYPE where description='Alteration'),'1','0', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where description='New Possession certificate' and checklisttypeid = (select id from eg_checklist_type where code='OWNERSHIPDOCUMENTS' )), (select id from EGBPA_MSTR_SERVICETYPE where description='Alteration'),'1','0', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where description='New Land tax receipt' and checklisttypeid = (select id from eg_checklist_type where code='OWNERSHIPDOCUMENTS' )), (select id from EGBPA_MSTR_SERVICETYPE where description='Alteration'),'1','0', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where description='Building permit' and checklisttypeid = (select id from eg_checklist_type where code='OWNERSHIPDOCUMENTS' )), (select id from EGBPA_MSTR_SERVICETYPE where description='Alteration'),'1','0', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where description='Stage Photos' and checklisttypeid = (select id from eg_checklist_type where code='OWNERSHIPDOCUMENTS' )), (select id from EGBPA_MSTR_SERVICETYPE where description='Alteration'),'1','0', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where description='Other' and checklisttypeid = (select id from eg_checklist_type where code='OWNERSHIPDOCUMENTS' )), (select id from EGBPA_MSTR_SERVICETYPE where description='Alteration'),'1','0', 0, 1, now(), 1, now());



----------------------------------Addition or Extension--------------------------------------

INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where description='Application duly signed by the owner' and checklisttypeid = (select id from eg_checklist_type where code='OWNERSHIPDOCUMENTS' )), (select id from EGBPA_MSTR_SERVICETYPE where description='Addition or Extension'),'1','0', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where description='New land deed document' and checklisttypeid = (select id from eg_checklist_type where code='OWNERSHIPDOCUMENTS' )), (select id from EGBPA_MSTR_SERVICETYPE where description='Addition or Extension'),'1','0', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where description='New Possession certificate' and checklisttypeid = (select id from eg_checklist_type where code='OWNERSHIPDOCUMENTS' )), (select id from EGBPA_MSTR_SERVICETYPE where description='Addition or Extension'),'1','0', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where description='New Land tax receipt' and checklisttypeid = (select id from eg_checklist_type where code='OWNERSHIPDOCUMENTS' )), (select id from EGBPA_MSTR_SERVICETYPE where description='Addition or Extension'),'1','0', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where description='Building permit' and checklisttypeid = (select id from eg_checklist_type where code='OWNERSHIPDOCUMENTS' )), (select id from EGBPA_MSTR_SERVICETYPE where description='Addition or Extension'),'1','0', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where description='Stage Photos' and checklisttypeid = (select id from eg_checklist_type where code='OWNERSHIPDOCUMENTS' )), (select id from EGBPA_MSTR_SERVICETYPE where description='Addition or Extension'),'1','0', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where description='Other' and checklisttypeid = (select id from eg_checklist_type where code='OWNERSHIPDOCUMENTS' )), (select id from EGBPA_MSTR_SERVICETYPE where description='Alteration'),'1','0', 0, 1, now(), 1, now());



---------------------------------Change in occupancy-----------------------------------------

INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where description='Application duly signed by the owner' and checklisttypeid = (select id from eg_checklist_type where code='OWNERSHIPDOCUMENTS' )), (select id from EGBPA_MSTR_SERVICETYPE where description='Change in occupancy'),'1','0', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where description='New land deed document' and checklisttypeid = (select id from eg_checklist_type where code='OWNERSHIPDOCUMENTS' )), (select id from EGBPA_MSTR_SERVICETYPE where description='Change in occupancy'),'1','0', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where description='New Possession certificate' and checklisttypeid = (select id from eg_checklist_type where code='OWNERSHIPDOCUMENTS' )), (select id from EGBPA_MSTR_SERVICETYPE where description='Change in occupancy'),'1','0', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where description='New Land tax receipt' and checklisttypeid = (select id from eg_checklist_type where code='OWNERSHIPDOCUMENTS' )), (select id from EGBPA_MSTR_SERVICETYPE where description='Change in occupancy'),'1','0', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where description='Building permit' and checklisttypeid = (select id from eg_checklist_type where code='OWNERSHIPDOCUMENTS' )), (select id from EGBPA_MSTR_SERVICETYPE where description='Change in occupancy'),'1','0', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where description='Stage Photos' and checklisttypeid = (select id from eg_checklist_type where code='OWNERSHIPDOCUMENTS' )), (select id from EGBPA_MSTR_SERVICETYPE where description='Change in occupancy'),'1','0', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where description='Other' and checklisttypeid = (select id from eg_checklist_type where code='OWNERSHIPDOCUMENTS' )), (select id from EGBPA_MSTR_SERVICETYPE where description='Change in occupancy'),'1','0', 0, 1, now(), 1, now());




------------------------------OWNERSHIPREJECTIONREASON----------------------------------------------------



------------------------------------------    "New Construction"  ------------------------------------


INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='OWNERSHIPTRANSFERREJECTIONREASON-01' and checklisttypeid =(select id from eg_checklist_type where code='OWNERSHIPREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='01'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='OWNERSHIPTRANSFERREJECTIONREASON-02' and checklisttypeid =(select id from eg_checklist_type where code='OWNERSHIPREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='01'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='OWNERSHIPTRANSFERREJECTIONREASON-03' and checklisttypeid =(select id from eg_checklist_type where code='OWNERSHIPREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='01'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='OWNERSHIPTRANSFERREJECTIONREASON-04' and checklisttypeid =(select id from eg_checklist_type where code='OWNERSHIPREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='01'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='OWNERSHIPTRANSFERREJECTIONREASON-05' and checklisttypeid =(select id from eg_checklist_type where code='OWNERSHIPREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='01'), 'true', 'false', 0, 1, now(), 1, now());


-----------------------------------------  "Change in occupancy" -------------------------------------------------------------


INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='OWNERSHIPTRANSFERREJECTIONREASON-01' and checklisttypeid =(select id from eg_checklist_type where code='OWNERSHIPREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='07'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='OWNERSHIPTRANSFERREJECTIONREASON-02' and checklisttypeid =(select id from eg_checklist_type where code='OWNERSHIPREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='07'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='OWNERSHIPTRANSFERREJECTIONREASON-03' and checklisttypeid =(select id from eg_checklist_type where code='OWNERSHIPREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='07'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='OWNERSHIPTRANSFERREJECTIONREASON-04' and checklisttypeid =(select id from eg_checklist_type where code='OWNERSHIPREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='07'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='OWNERSHIPTRANSFERREJECTIONREASON-05' and checklisttypeid =(select id from eg_checklist_type where code='OWNERSHIPREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='07'), 'true', 'false', 0, 1, now(), 1, now());

----------------------------------   "Reconstruction"   ------------------------------


INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='OWNERSHIPTRANSFERREJECTIONREASON-01' and checklisttypeid =(select id from eg_checklist_type where code='OWNERSHIPREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='03'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='OWNERSHIPTRANSFERREJECTIONREASON-02' and checklisttypeid =(select id from eg_checklist_type where code='OWNERSHIPREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='03'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='OWNERSHIPTRANSFERREJECTIONREASON-03' and checklisttypeid =(select id from eg_checklist_type where code='OWNERSHIPREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='03'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='OWNERSHIPTRANSFERREJECTIONREASON-04' and checklisttypeid =(select id from eg_checklist_type where code='OWNERSHIPREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='03'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='OWNERSHIPTRANSFERREJECTIONREASON-05' and checklisttypeid =(select id from eg_checklist_type where code='OWNERSHIPREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='03'), 'true', 'false', 0, 1, now(), 1, now());

---------------------------------------------   "Alteration"   ---------------------------------------


INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='OWNERSHIPTRANSFERREJECTIONREASON-01' and checklisttypeid =(select id from eg_checklist_type where code='OWNERSHIPREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='04'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='OWNERSHIPTRANSFERREJECTIONREASON-02' and checklisttypeid =(select id from eg_checklist_type where code='OWNERSHIPREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='04'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='OWNERSHIPTRANSFERREJECTIONREASON-03' and checklisttypeid =(select id from eg_checklist_type where code='OWNERSHIPREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='04'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='OWNERSHIPTRANSFERREJECTIONREASON-04' and checklisttypeid =(select id from eg_checklist_type where code='OWNERSHIPREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='04'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='OWNERSHIPTRANSFERREJECTIONREASON-05' and checklisttypeid =(select id from eg_checklist_type where code='OWNERSHIPREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='04'), 'true', 'false', 0, 1, now(), 1, now());


---------------------------------------------------"Addition or Extension" ----------------------------------------



INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='OWNERSHIPTRANSFERREJECTIONREASON-01' and checklisttypeid =(select id from eg_checklist_type where code='OWNERSHIPREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='06'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='OWNERSHIPTRANSFERREJECTIONREASON-02' and checklisttypeid =(select id from eg_checklist_type where code='OWNERSHIPREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='06'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='OWNERSHIPTRANSFERREJECTIONREASON-03' and checklisttypeid =(select id from eg_checklist_type where code='OWNERSHIPREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='06'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='OWNERSHIPTRANSFERREJECTIONREASON-04' and checklisttypeid =(select id from eg_checklist_type where code='OWNERSHIPREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='06'), 'true', 'false', 0, 1, now(), 1, now());
INSERT INTO egbpa_checklist_servicetype_mapping(id, checklist, servicetype, isrequired, ismandatory, version, createdby, createddate, lastmodifiedby,lastmodifieddate) VALUES (nextval('seq_egbpa_checklist_servicetype_mapping'), (select id from eg_checklist where code='OWNERSHIPTRANSFERREJECTIONREASON-05' and checklisttypeid =(select id from eg_checklist_type where code='OWNERSHIPREJECTIONREASONS') ),(select id from EGBPA_MSTR_SERVICETYPE where code='06'), 'true', 'false', 0, 1, now(), 1, now());



