
create table EGBPA_OWNERSHIP_FEE
	(
	  id bigint NOT NULL,
	  OWNERSHIPTRANSFER bigint,
	  APPLICATIONFEE bigint,
	  createdby bigint NOT NULL,
      createddate timestamp without time zone NOT NULL,
 	  lastModifiedDate timestamp without time zone,
 	  lastModifiedBy bigint,
	  version numeric NOT NULL,
	  CONSTRAINT PK_OWNERSHIP_FEE_ID PRIMARY KEY (ID),
	  CONSTRAINT FK_EGBPA_OWNERSHIP_FEE_APPL FOREIGN KEY (OWNERSHIPTRANSFER) REFERENCES EGBPA_OWNERSHIP_TRANSFER(ID),
	  CONSTRAINT FK_EGBPA_OWNERSHIP_FEE_APPLFEE FOREIGN KEY (APPLICATIONFEE) REFERENCES EGBPA_APPLICATION_FEE(ID),
	  CONSTRAINT FK_EGBPA_OWNERSHIP_FEE_MDFDBY FOREIGN KEY (lastModifiedBy) REFERENCES state.EG_USER (ID),
      CONSTRAINT FK_EGBPA_OWNERSHIP_FEE_CRTBY FOREIGN KEY (createdBy)REFERENCES state.EG_USER (ID)
        );
 create sequence SEQ_EGBPA_OWNERSHIP_FEE;

