INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate)
 VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'BpaApplication', 'Scheduled For Document Scrutiny', NULL, 'Pending For Auto Rescheduling Document Scrutiny', null, 'CREATEBPAAPPLICATION', 'Scheduled For Document Scrutiny', 'Initiated For Auto Rescheduling Appointment', 'Section Clerk', 'Pending For Rescheduling For Document Scrutiny', 'Forward,Initiate Rejection', NULL, NULL, '2017-01-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate)
 VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'BpaApplication', 'Rescheduled For Document Scrutiny', NULL, 'Pending For Auto Rescheduling Document Scrutiny', null, 'CREATEBPAAPPLICATION', 'Rescheduled For Document Scrutiny', 'Initiated For Auto Rescheduling Appointment', 'Section Clerk', 'Pending For Rescheduling For Document Scrutiny', 'Forward,Initiate Rejection', NULL, NULL, '2017-01-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate)
 VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'BpaApplication', 'Scheduled For Document Scrutiny', NULL, 'Initiated For Auto Rescheduling Appointment', null, 'CREATEBPAAPPLICATION', 'Rescheduled For Document Scrutiny', 'Document verification pending', 'Section Clerk', 'Rescheduled For Document Scrutiny', 'Forward,Initiate Rejection', NULL, NULL, '2017-01-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate)
 VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'BpaApplication', 'Rescheduled For Document Scrutiny', NULL, 'Initiated For Auto Rescheduling Appointment', null, 'CREATEBPAAPPLICATION', 'Rescheduled For Document Scrutiny', 'Document verification pending', 'Section Clerk', 'Rescheduled For Document Scrutiny', 'Forward,Initiate Rejection', NULL, NULL, '2017-01-01', '2099-04-01');