delete from eg_wf_matrix where objecttype = 'BpaApplication' and additionalrule='Low Risk';

insert into eg_wf_matrix(id, department, objecttype, currentstate, nextstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextaction, nextdesignation, nextstatus, validactions, fromdate, todate, version) values (nextval('seq_eg_wf_matrix'), 'ANY', 'BpaApplication', 'Scheduled For Document Scrutiny', 'Scheduled For Document Scrutiny', '', 'Pending For Auto Rescheduling Document Scrutiny', '', 'Low Risk', 'Initiated For Auto Rescheduling Appointment', 'Section Clerk', 'Pending For Rescheduling For Document Scrutiny', 'Forward', '2019-01-01', '2099-04-01',0);
insert into eg_wf_matrix(id, department, objecttype, currentstate, nextstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextaction, nextdesignation, nextstatus, validactions, fromdate, todate, version) values (nextval('seq_eg_wf_matrix'), 'ANY', 'BpaApplication', 'Rescheduled For Document Scrutiny', 'Rescheduled For Document Scrutiny', '', 'Pending For Auto Rescheduling Document Scrutiny', '', 'Low Risk', 'Initiated For Auto Rescheduling Appointment', 'Section Clerk', 'Pending For Rescheduling For Document Scrutiny', 'Forward', '2019-01-01', '2099-04-01',0);
insert into eg_wf_matrix(id, department, objecttype, currentstate, nextstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextaction, nextdesignation, nextstatus, validactions, fromdate, todate, version) values (nextval('seq_eg_wf_matrix'), 'ANY', 'BpaApplication', 'Scheduled For Document Scrutiny', 'Rescheduled For Document Scrutiny', '', 'Initiated For Auto Rescheduling Appointment', '', 'Low Risk', 'Document verification pending', 'Section Clerk', 'Rescheduled For Document Scrutiny', 'Forward', '2019-01-01', '2099-04-01',0);
insert into eg_wf_matrix(id, department, objecttype, currentstate, nextstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextaction, nextdesignation, nextstatus, validactions, fromdate, todate, version) values (nextval('seq_eg_wf_matrix'), 'ANY', 'BpaApplication', 'Rescheduled For Document Scrutiny', 'Rescheduled For Document Scrutiny', '', 'Initiated For Auto Rescheduling Appointment', '', 'Low Risk', 'Document verification pending', 'Section Clerk', 'Rescheduled For Document Scrutiny', 'Forward', '2019-01-01', '2099-04-01',0);
insert into eg_wf_matrix(id, department, objecttype, currentstate, nextstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextaction, nextdesignation, nextstatus, validactions, fromdate, todate, version) values (nextval('seq_eg_wf_matrix'), 'ANY', 'BpaApplication', 'Document Verified', 'Field Inspection completed', '', '', '', 'Low Risk', 'Forwarded to Assistant Engineer Approval', 'Assistant engineer', 'Field Inspected', 'Forward', '2019-01-01', '2099-04-01',0);
insert into eg_wf_matrix(id, department, objecttype, currentstate, nextstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextaction, nextdesignation, nextstatus, validactions, fromdate, todate, version) values (nextval('seq_eg_wf_matrix'), 'ANY', 'BpaApplication', 'NEW', 'Registered', '', 'Forward to section clerk is pending', '', 'Low Risk', 'Forwarded to section clerk', 'Section Clerk', 'Registered', 'Forward', '2019-01-01', '2099-04-01',0);
insert into eg_wf_matrix(id, department, objecttype, currentstate, nextstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextaction, nextdesignation, nextstatus, validactions, fromdate, todate, version) values (nextval('seq_eg_wf_matrix'), 'ANY', 'BpaApplication', 'Registered', 'Section clerk approved', 'Registered', 'Forwarded to section clerk', '', 'Low Risk', 'Forwarded to Overseer for field inspection', 'Town Planning Building Overseer', 'Registered', 'Forward', '2019-01-01', '2099-04-01',0);
insert into eg_wf_matrix(id, department, objecttype, currentstate, nextstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextaction, nextdesignation, nextstatus, validactions, fromdate, todate, version) values (nextval('seq_eg_wf_matrix'), 'ANY', 'BpaApplication', 'Section clerk approved', 'Field Inspection completed', 'Registered', 'Forwarded to Overseer for field inspection', '', 'Low Risk', 'Forwarded to Assistant Engineer Approval', 'Assistant engineer', 'Field Inspected', 'Forward', '2019-01-01', '2099-04-01',0);
insert into eg_wf_matrix(id, department, objecttype, currentstate, nextstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextaction, nextdesignation, nextstatus, validactions, fromdate, todate, version) values (nextval('seq_eg_wf_matrix'), 'ANY', 'BpaApplication', 'Field Inspection completed', 'NOC updation in progress', '', '', '', 'Low Risk', 'Forwarded to Superintendent for Noc Updation', 'Superintendent', 'Field Inspected', 'Forward,Revert', '2019-01-01', '2099-04-01',0);
insert into eg_wf_matrix(id, department, objecttype, currentstate, nextstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextaction, nextdesignation, nextstatus, validactions, fromdate, todate, version) values (nextval('seq_eg_wf_matrix'), 'ANY', 'BpaApplication', 'NOC updation in progress', 'Application Approval Pending', '', '', '', 'Low Risk', 'Forwarded to Assistant Engineer For Approval', 'Assistant engineer', 'NOC Updated', 'Forward', '2019-01-01', '2099-04-01',0);
insert into eg_wf_matrix(id, department, objecttype, currentstate, nextstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextaction, nextdesignation, nextstatus, validactions, fromdate, todate, version) values (nextval('seq_eg_wf_matrix'), 'ANY', 'BpaApplication', 'Application Approval Pending', 'Final Approval Process initiated', '', 'Forwarded to Assistant Engineer For Approval', '', 'Low Risk', 'END', 'Assistant engineer', 'Order Issued to Applicant', 'Approve,Revert,Revoke Permit', '2019-01-01', '2099-04-01',0);

insert into eg_wf_matrix(id, department, objecttype, currentstate, nextstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextaction, nextdesignation, nextstatus, validactions, fromdate, todate, version) values (nextval('seq_eg_wf_matrix'), 'ANY', 'BpaApplication', 'Record Approved', 'END', '', '', '', 'Low Risk', 'END', 'Superintendent', 'Order Issued to Applicant', 'Generate Permit Order', '2019-01-01', '2099-04-01',0);
insert into eg_wf_matrix(id, department, objecttype, currentstate, nextstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextaction, nextdesignation, nextstatus, validactions, fromdate, todate, version) values (nextval('seq_eg_wf_matrix'), 'ANY', 'BpaApplication', 'LP Initiated', 'LP Created', '', '', '', 'Low Risk', 'Letter To Party Reply Pending', 'Section Clerk', 'Letter To Party Created', 'Forward', '2019-01-01', '2099-04-01',0);
insert into eg_wf_matrix(id, department, objecttype, currentstate, nextstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextaction, nextdesignation, nextstatus, validactions, fromdate, todate, version) values (nextval('seq_eg_wf_matrix'), 'ANY', 'BpaApplication', 'LP Created', 'LP Reply Received', '', '', '', 'Low Risk', 'Forward to LP Initiator pending', 'LP Raised', 'Letter To Party Reply Received', 'Forward', '2019-01-01', '2099-04-01',0);

insert into eg_wf_matrix(id, department, objecttype, currentstate, nextstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextaction, nextdesignation, nextstatus, validactions, fromdate, todate, version) values (nextval('seq_eg_wf_matrix'), 'ANY', 'BpaApplication', 'Town Surveyor Inspection Initiated', 'Town Surveyor Inspection Initiated', '', 'AE Approval Pending', '', 'Low Risk', 'Forwarded to Town Surveyor For Additional Inspection', 'Town Surveyor', 'Town Surveyor Inspection Initiated', 'Forward', '2019-01-01', '2099-04-01',0);
insert into eg_wf_matrix(id, department, objecttype, currentstate, nextstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextaction, nextdesignation, nextstatus, validactions, fromdate, todate, version) values (nextval('seq_eg_wf_matrix'), 'ANY', 'BpaApplication', 'Town Surveyor Inspection Initiated', 'Town Surveyor Inspection Completed', '', 'Town Surveyor Approval Pending', '', 'Low Risk', 'Forwarded to town surveyor inspection initiator approval', 'Town Planning Building Overseer', 'Town Surveyor Inspected', 'Forward', '2019-01-01', '2099-04-01',0);
insert into eg_wf_matrix(id, department, objecttype, currentstate, nextstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextaction, nextdesignation, nextstatus, validactions, fromdate, todate, version) values (nextval('seq_eg_wf_matrix'), 'ANY', 'BpaApplication', 'Town Surveyor Inspection Completed', 'Field Inspection completed', '', 'Forwarded to Overseer', '', 'Low Risk', 'Forwarded to Assistant Engineer Approval', 'Assistant engineer', 'Field Inspected', 'Forward', '2019-01-01', '2099-04-01',0);
insert into eg_wf_matrix(id, department, objecttype, currentstate, nextstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextaction, nextdesignation, nextstatus, validactions, fromdate, todate, version) values (nextval('seq_eg_wf_matrix'), 'ANY', 'BpaApplication', 'Town Surveyor Inspection Completed', 'NOC updation in progress', '', 'Forwarded to Assistant Engineer', '', 'Low Risk', 'Forwarded to Superintendent for Noc Updation', 'Superintendent', 'Field Inspected', 'Forward', '2019-01-01', '2099-04-01',0);