alter table egbpa_dcr_document add column isAutoPopulated boolean default false;


---- Application configuration DML----------------
INSERT INTO eg_appconfig ( ID, KEY_NAME, DESCRIPTION, VERSION, MODULE ) VALUES
(nextval('SEQ_EG_APPCONFIG'), 'DCR_DOC_AUTO_POPULATE_UPLOAD', 'Will auto populate documents which are generated by system during plan scrutiny',0, (select id from eg_module where name='BPA'));

INSERT INTO eg_appconfig_values ( ID, KEY_ID, EFFECTIVE_FROM, VALUE, VERSION )
VALUES (nextval('SEQ_EG_APPCONFIG_VALUES'),(SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='DCR_DOC_AUTO_POPULATE_UPLOAD'
 AND MODULE =(select id from eg_module where name='BPA')),current_date, 'NO',0);

INSERT INTO eg_appconfig ( ID, KEY_NAME, DESCRIPTION, VERSION, MODULE ) VALUES
(nextval('SEQ_EG_APPCONFIG'), 'DCR_DOC_MANUAL_UPLOAD', 'User need to upload dcr documents',0, (select id from eg_module where name='BPA'));

INSERT INTO eg_appconfig_values ( ID, KEY_ID, EFFECTIVE_FROM, VALUE, VERSION )
VALUES (nextval('SEQ_EG_APPCONFIG_VALUES'),(SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='DCR_DOC_MANUAL_UPLOAD'
 AND MODULE =(select id from eg_module where name='BPA')),current_date, 'YES',0);

INSERT INTO eg_appconfig ( ID, KEY_NAME, DESCRIPTION, VERSION, MODULE ) VALUES
(nextval('SEQ_EG_APPCONFIG'), 'DCR_DOC_AUTO_POPULATE_AND_MANUAL_UPLOAD', 'Will auto populate documents which are generated by system  as well as user will upload if any not generated properly',0, (select id from eg_module where name='BPA'));

INSERT INTO eg_appconfig_values ( ID, KEY_ID, EFFECTIVE_FROM, VALUE, VERSION )
VALUES (nextval('SEQ_EG_APPCONFIG_VALUES'),(SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='DCR_DOC_AUTO_POPULATE_AND_MANUAL_UPLOAD'
 AND MODULE =(select id from eg_module where name='BPA')),current_date, 'NO',0);