
INSERT INTO EG_ROLEACTION (ACTIONID, ROLEID)
SELECT ACTIONID, ROLEID FROM TEMP_EG_ROLEACTION;

DROP TABLE TEMP_EG_ROLEACTION;

ALTER TABLE  eg_roleaction ADD CONSTRAINT fk_role_id FOREIGN KEY (roleid) REFERENCES state.eg_role(id);